name: Init
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim-buster
      options: --rm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: pip install poetry==1.2.2

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest
